### ISSUE TITLE
[tracking] Upstream architecture math support

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#176]
These are some compiler/toolchain developments for DSP math of varying usefulness. Let this issue track the different moving pieces of machine level math support.

* [x] M7 instruction schedule pending in LLVM: https://reviews.llvm.org/D91355, Targeting Rust 1.53.0
* [x] math intrinsics (especially for us: `vminnm`, `vmaxnm`, `vsqrt`, `vabs`, `vrintr`)
* [x] M7 `+fp-armv8d16` target feature in LLVM and vfpv5, see ARM.td.
* [x] review ABI choice w.r.t. FP
