### ISSUE TITLE
Pounder power detector temperature readout

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#375]
* [x] pounder temperature measurement using the power detectors (https://github.com/sinara-hw/Pounder/issues/94)
* [ ] use for pounder presence detection instead of pgood
* [x] read and telemetrize CPU temperature as well (#575)
* [x] provide API for temperature readout (#837)

![image](https://user-images.githubusercontent.com/1338946/120660622-ce8e6680-c487-11eb-8d69-35a2899b5856.png)

**Comment by jordens** [comment]
Working fine in FLS.
