### ISSUE TITLE
doc: TODO

### ISSUE THREAD

**Issue by jordens** [quartiq/stabilizer#403]
Unsorted docs items after #401:

* [ ] cache deadlinks and ruby stuff (like https://bsmth.de/blog/deploying-jekyll-github-actions-aws-amplify) to speed up CI
* [x] deadlinks `--check-http --check-intra-doc-links`
* [x] add docs to bors requirements
